SET LOGPATH="%cd%\log"
SET SOURCE="%SYSTEMDRIVE%/%HOMEPATH%/Documents"
SET DESTINATION="%cd%\bak"
ROBOCOPY.EXE /R:0 /W:0 "%SOURCE%" "%DESTNATION%" /E /Z /XA:SH /XJ /UNICODE /ETA /COPY:DT /MIR /MT:32 /UNILOG+"%LOGPATH%\backup.log" /TEE /XF "%LOGPATH%\backup.log"
PAUSE